### ISSUE TITLE
Question, not issue

### ISSUE THREAD

**Issue by ovaltzer** [beefsack/go-rate#9]
hey there - quick question:
how will the package deal with changing clocks? i.e. started with clock of unix initial time and then after some time change to actual UTC time (jump in time forward)?
thanks!

**Comment by beefsack** [comment]
The library uses the native time module, so it would depend on how that module handles system time changes. My assumption would be if system time changes then it would impact the rate limiter, though things like automated DST changeovers should not impact the rate limiter.

If system time is changing by a significant amount, there may be other issues at hand.
